name: update readme
on: push
jobs:
  readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"
          architecture: "x64"
      - name: pip setting
        run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: run python
        run: |
          python chunirec.py
      - name: commit files
        run: |
          git config --global user.name "$github-actions[bot]"
          git config --global user.email "$github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m 'update README.md'
          git push origin main
